# Generated by Django 4.2.5 on 2023-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_answer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
