# Generated by Django 4.2.5 on 2023-10-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0004_remove_answer_question_remove_answer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
